# https://help.xmatters.com/ondemand/epic/included%20files.htm
DS_EMAIL_DEVICES:
  EXTERNAL_KEY: TEXT
  ADDRESS: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_EVENT_DOMAIN_PREDICATES:
  EXTERNAL_KEY: TEXT
  PREDICATE_NAME: TEXT
  EVENT_DOMAIN_KEY: TEXT
  PREDICATE_TYPE: TEXT
  IMPORTANT: TEXT
  REQUIRED: TEXT
  VALIDATE: TEXT
  PATTERN: TEXT
  ACTION: TEXT
  IS_EXTERNALLY_OWNED: TEXT

DS_FAX_DEVICES:
  EXTERNAL_KEY: TEXT
  FAX_NUMBER: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  ACTION: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  COUNTRY_CODE: TEXT

DS_GROUPS:
  EXTERNAL_KEY: TEXT
  GROUP_NAME: TEXT
  DESCRIPTION: TEXT
  STATUS: TEXT
  USE_DEFAULT_DEVICES: TEXT
  TIMEZONE: TEXT
  GROUP_SITE_NAME: TEXT
  OBSERVED_BY_ALL: TEXT
  OBSERVER_LIST: TEXT
  SUPERVISOR_LIST: TEXT
  ALLOW_DUPLICATES: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_PERSON_SUPERVISORS:
  USER_EXTERNAL_KEY: TEXT
  PERSON_SUPERVISOR_LIST: TEXT
  ACTION: TEXT

DS_PREDICATE_JOIN_VALUES:
  PREDICATE_EXTERNAL_KEY: TEXT
  PREDICATE_VALUE: TEXT

DS_SITES:
  EXTERNAL_KEY: TEXT
  SITENAME: TEXT
  SITE_STATUS: TEXT
  SITE_LANGUAGE: TEXT
  SITE_TIMEZONE: TEXT
  SITE_ADDRESS_01: TEXT
  SITE_ADDRESS_02: TEXT
  SITE_CITY: TEXT
  SITE_COUNTRY: TEXT
  SITE_REGION_NAME: TEXT
  SITE_MAIL_CODE: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_TEAM_MEMBERSHIPS:
  TEAM_KEY: TEXT
  MEMBER_KEY: TEXT
  MEMBER_TYPE: TEXT
  MEMBER_SUB_TYPE: TEXT
  MEMBER_SEQUENCE_NUMBER: TEXT
  IS_EXTERNALLY_OWNED: TEXT

DS_TEAMS:
  EXTERNAL_KEY: TEXT
  GROUP_KEY: TEXT
  SUB_TARGET_NAME: TEXT
  DESCRIPTION: TEXT
  USE_DEFAULT_DEVICES: TEXT
  ESCALATION_SCHEDULE: TEXT
  IS_ROUND_ROBIN: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_TEXT_PAGER_DEVICES:
  EXTERNAL_KEY: TEXT
  PIN: TEXT
  IS_TWO_WAY: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  SERVICE_PROVIDER_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_TEXT_PHONE_DEVICES:
  EXTERNAL_KEY: TEXT
  TARGET_NUMBER: TEXT
  COUNTRY_CODE: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_USER_CUSTOM_VALUES:
  EXTERNAL_KEY: TEXT
  CUSTOM_USER_KEY: TEXT
  FIELD_KEY: TEXT
  CUSTOM_VALUE: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_USER_JOIN_ATTRIBUTES:
  USER_EXTERNAL_KEY: TEXT
  ATTRIBUTE_EXTERNAL_KEY: TEXT

DS_USERS:
  EXTERNAL_KEY: TEXT
  USER_ID: TEXT
  FIRST_NAME: TEXT
  LAST_NAME: TEXT
  STATUS: TEXT
  ROLE_LIST: TEXT
  SITE_NAME: TEXT
  LANGUAGE_OVERRIDE: TEXT
  TIMEZONE_OVERRIDE: TEXT
  RECORDED_NAME: TEXT
  WEB_LOGIN: TEXT
  PHONE_LOGIN: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_VOICE_DEVICES:
  EXTERNAL_KEY: TEXT
  COUNTRY: TEXT
  AREA_CODE: TEXT
  PHONE_NUMBER: TEXT
  EXTENSION: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT

DS_VOICE_IVR_DEVICES:
  EXTERNAL_KEY: TEXT
  COUNTRY: TEXT
  AREA_CODE: TEXT
  PHONE_NUMBER: TEXT
  EXTENSION: TEXT
  USER_KEY: TEXT
  DEVICE_NAME: TEXT
  STATUS: TEXT
  DEFAULT_DEVICE: TEXT
  DEVICE_ORDER: TEXT
  DELAY: TEXT
  LOCK_24x7: TEXT
  IS_EXTERNALLY_OWNED: TEXT
  ACTION: TEXT
